### ISSUE TITLE
Using tap-min with the api

### ISSUE THREAD

**Issue by Josema** [gummesson/tap-min#2]
Hello, is there a way to use tap-min with the api like https://github.com/scottcorgan/tap-spec does?

``` javascript
var test = require('tape');
var tapSpec = require('tap-spec');

test.createStream()
  .pipe(tapSpec())
  .pipe(process.stdout);
```

Is because I need to pass arguments on the `npm test` command:
http://stackoverflow.com/questions/35221098/passing-arguments-to-npm-script-in-package-json

**Comment by gummesson** [comment]
Hi,

It's currently not possible, although I might take a stab at it this weekend. 
Pull requests are always welcome too. :)

**Comment by Josema** [comment]
I will waste more time doing it than you. But if you don't have time maybe I will give a try. Thanks for the quick response.

**Comment by gummesson** [comment]
I just published a new version, which should support your use case. Let me know if it works! :)

**Comment by Josema** [comment]
Working! Thanks :)
